// <auto-generated />
using System;
using JobSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobSearch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JobSearchDbContext))]
    [Migration("20260925185619_AddReviewWorkflow")]
    partial class AddReviewWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.FetchStateEntity", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSuccessfulFetchUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Source");

                    b.ToTable("FetchStates", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompensationDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateAppliedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateFoundUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DatePostedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimatedHoursPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLikelyStaffingAgency")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaximumHourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumHourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCompany")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresSecurityClearance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoreReasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkLocationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Score");

                    b.HasIndex("NormalizedCompany", "NormalizedTitle");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Source", "SourceKey")
                        .IsUnique();

                    b.ToTable("JobSources", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OldStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "ChangedAtUtc");

                    b.ToTable("JobStatusHistory", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobSourceEntity", b =>
                {
                    b.HasOne("JobSearch.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany("Sources")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobStatusHistoryEntity", b =>
                {
                    b.HasOne("JobSearch.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany("StatusHistory")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.Navigation("Sources");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
