// <auto-generated />
using System;
using JobSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobSearch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JobSearchDbContext))]
    [Migration("20260927202418_AddCareerProfileAndResumeEvidence")]
    partial class AddCareerProfileAndResumeEvidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ApplicationAnswerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlwaysRequireConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("AnswerType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedPattern")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPattern")
                        .IsUnique();

                    b.ToTable("ApplicationAnswers", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoSubmitApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomationMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrowserRunId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldsFilledJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PreparedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ApplicationEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "OccurredAtUtc");

                    b.ToTable("ApplicationEvents", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ApplicationQuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftAnswer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedQuestion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "IsResolved");

                    b.ToTable("ApplicationQuestions", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.CareerProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("CareerProfiles", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.CareerProfileQuestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AnsweredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmploymentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CareerProfileQuestions", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.FetchStateEntity", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastFailedFetchUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFailure")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessfulFetchUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Source");

                    b.ToTable("FetchStates", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompensationDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateAppliedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateFoundUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DatePostedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EligibilityProblemsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("EligibilityUnknownsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimatedHoursPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeenUnixSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLikelyStaffingAgency")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaximumHourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumHourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCompany")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresSecurityClearance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoreReasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceBoard")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFeedKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkLocationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FirstSeenUnixSeconds");

                    b.HasIndex("Score");

                    b.HasIndex("NormalizedCompany", "NormalizedTitle");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobFitAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CareerProfileVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallFit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "CreatedAtUtc");

                    b.ToTable("JobFitAnalyses", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenUnixSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("FeedKey", "FirstSeenUnixSeconds");

                    b.HasIndex("Source", "Board", "SourceKey")
                        .IsUnique();

                    b.ToTable("JobSources", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OldStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "ChangedAtUtc");

                    b.ToTable("JobStatusHistory", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ResumeArtifactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CareerProfileVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Kind", "GeneratedAtUtc");

                    b.ToTable("ResumeArtifacts", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ResumeImportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ResumeImports", (string)null);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ApplicationEntity", b =>
                {
                    b.HasOne("JobSearch.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ApplicationEventEntity", b =>
                {
                    b.HasOne("JobSearch.Infrastructure.Persistence.Entities.ApplicationEntity", "Application")
                        .WithMany("Events")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ApplicationQuestionEntity", b =>
                {
                    b.HasOne("JobSearch.Infrastructure.Persistence.Entities.ApplicationEntity", "Application")
                        .WithMany("Questions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobFitAnalysisEntity", b =>
                {
                    b.HasOne("JobSearch.Infrastructure.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobSourceEntity", b =>
                {
                    b.HasOne("JobSearch.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany("Sources")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobStatusHistoryEntity", b =>
                {
                    b.HasOne("JobSearch.Infrastructure.Persistence.Entities.JobEntity", "Job")
                        .WithMany("StatusHistory")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ResumeArtifactEntity", b =>
                {
                    b.HasOne("JobSearch.Infrastructure.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.ApplicationEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("JobSearch.Infrastructure.Persistence.Entities.JobEntity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Sources");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
